/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.Admin;

import client.utils.Utils;
import java.awt.*;
import java.io.File;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import raven.swing.AvatarIcon;
import services.boarding_houses.BoardingHouseService;
import services.boarding_houses.entities.BoardingHouseEntity;

/**
 * @author ACER
 */
public class MenuKost extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    public boolean databaru;
    //	file image to be uploaded
    File imageFile;

    String image = new BoardingHouseEntity().getImage();

    public MenuKost() {
        initComponents();
        databaru = true;
        jTextField1.setEnabled(false); // disable textfield image
        txtId.setEnabled(false); // disable textfield id
        tblKost.setModel(BoardingHouseService.getData());
        tblKostAwal.setModel(BoardingHouseService.getDataKost());

        // icon input form kost
        nameKost.setIcon(new javax.swing.ImageIcon("./img/nama-kost.png"));
        iconAlamat.setIcon(new javax.swing.ImageIcon("./img/alamat.png"));
        iconUkuran.setIcon(new javax.swing.ImageIcon("./img/ukuran.png"));
        iconHarga.setIcon(new javax.swing.ImageIcon("./img/harga.png"));
        iconDeskripsi.setIcon(new javax.swing.ImageIcon("./img/Deskripsi.png"));
        iconJumlahKamar.setIcon(new javax.swing.ImageIcon("./img/quantity.png"));
        iconKategori.setIcon(new javax.swing.ImageIcon("./img/kategori.png"));
        iconKategori1.setIcon(new javax.swing.ImageIcon("./img/gambar.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKostAwal = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        txtSearchKost = new javax.swing.JTextField();
        panelTambah = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnDataKost = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        txtNamaKost = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtUkuran = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        spinnerQuantity = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        nameKost = new javax.swing.JLabel();
        iconAlamat = new javax.swing.JLabel();
        iconUkuran = new javax.swing.JLabel();
        iconHarga = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblKost = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconDeskripsi = new javax.swing.JLabel();
        iconJumlahKamar = new javax.swing.JLabel();
        iconKategori = new javax.swing.JLabel();
        iconKategori1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel10.setText("Dashboard > Kost");

        tblKostAwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKostAwal);

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel18.setText("Daftar Kost");

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel19.setText("KOST");

        btnTambah.setBackground(new java.awt.Color(0, 51, 153));
        btnTambah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah Kost");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        txtSearchKost.setText("Search");
        txtSearchKost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchKostMouseClicked(evt);
            }
        });
        txtSearchKost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKostKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelViewLayout.createSequentialGroup()
                                    .addGap(317, 317, 317)
                                    .addComponent(jLabel18)))
                            .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSearchKost, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(txtSearchKost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card3");

        panelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel12.setText("Dashboard > Kost");

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel21.setText("Form Tambah Kost");

        btnDataKost.setBackground(new java.awt.Color(0, 51, 153));
        btnDataKost.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnDataKost.setForeground(new java.awt.Color(255, 255, 255));
        btnDataKost.setText("Data Kost");
        btnDataKost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKostActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        btnBatal.setBackground(new java.awt.Color(255, 153, 0));
        btnBatal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtNamaKost.setText("Nama Kost");
        txtNamaKost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNamaKostMouseClicked(evt);
            }
        });

        txtAlamat.setText("Alamat");
        txtAlamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlamatMouseClicked(evt);
            }
        });

        txtUkuran.setText("Ukuran");
        txtUkuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUkuranMouseClicked(evt);
            }
        });
        txtUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkuranActionPerformed(evt);
            }
        });

        txtHarga.setText("Harga");
        txtHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHargaMouseClicked(evt);
            }
        });
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 51, 153));
        btnSimpan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        txtDeskripsi.setText("Deskripsi Kost");
        txtDeskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDeskripsiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(txtDeskripsi);

        btnUpload.setBackground(new java.awt.Color(0, 255, 204));
        btnUpload.setText("Upload Picture");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", "Campur" }));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        nameKost.setText(" ");

        iconAlamat.setText(" ");

        iconUkuran.setText(" ");

        iconHarga.setText(" ");

        tblKost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblKost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKostMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblKost);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA KOS");

        iconDeskripsi.setText(" ");

        iconJumlahKamar.setText(" ");

        iconKategori.setText(" ");

        iconKategori1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(299, 299, 299))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameKost, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(iconAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconUkuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaKost)
                            .addComponent(txtAlamat)
                            .addComponent(txtUkuran)
                            .addComponent(txtHarga)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iconKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(iconKategori1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iconJumlahKamar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerQuantity)
                            .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaKost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameKost)
                    .addComponent(iconJumlahKamar))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconAlamat)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconKategori))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconUkuran)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconHarga)
                            .addComponent(iconKategori1))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconDeskripsi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnBatal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(213, 213, 213))
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(20, 20, 20))
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDataKost, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnDataKost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        panelMain.add(panelTambah, "card4");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

	private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(panelTambah);
        panelMain.repaint();
        panelMain.revalidate();
	}//GEN-LAST:event_btnTambahActionPerformed

	private void btnDataKostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKostActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
	}//GEN-LAST:event_btnDataKostActionPerformed

    /**
     * This method is triggered when the "Upload" button is clicked. It opens a
     * file chooser dialog to select an image file. The selected image file is
     * then displayed in a label and its name is set in a text field. If no
     * image file is selected, a message is displayed in the text field. If an
     * error occurs during the process, an error message dialog is shown.
     */
	private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        try {
            // Create a JFileChooser instance to select a file
            JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            // Disable the option to select all file types
            fileChooser.setAcceptAllFileFilterUsed(false);
            // Set the title of the file chooser dialog
            fileChooser.setDialogTitle("Select a image file");
            // Create a FileNameExtensionFilter to only allow .jpg and .png files
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Only .jpg or .png files", "jpg", "jpeg", "png");
            // Add the filter to the file chooser
            fileChooser.addChoosableFileFilter(filter);
            // Show the file chooser dialog and get the result
            int result = fileChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                // If a file was selected
                // Get the selected file
                imageFile = fileChooser.getSelectedFile();
                // Print the absolute path of the selected file
                System.out.println(new ImageIcon(String.valueOf(fileChooser.getSelectedFile())));
                // Create an ImageIcon from the selected file
                ImageIcon ic = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
                // Set the ImageIcon as the icon of the label
                labelImage.setIcon(new AvatarIcon(ic, 100, 100, 5));
                // Set the name of the selected file in the text field
                jTextField1.setText(fileChooser.getSelectedFile().getName());
            } else {
                // If no file was selected
                imageFile = fileChooser.getSelectedFile();
                jTextField1.setText("Batal memilih gambar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Upload" + e);
        }
	}//GEN-LAST:event_btnUploadActionPerformed

	private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        // validate save or update
        if (databaru) // new data
        {
            try {
                BoardingHouseEntity kostData = new BoardingHouseEntity();

                kostData.setName(txtNamaKost.getText());
                kostData.setImage(String.valueOf(imageFile));
                kostData.setSize(txtUkuran.getText());

                // Validate if the input for price is a number
                String priceText = txtHarga.getText();
                if (!priceText.matches("\\d+")) { // Check if the input contains only digits
                    JOptionPane.showMessageDialog(null, "Input harga harus angka");
                    return; // Exit the method
                }
                kostData.setPrice(Integer.parseInt(priceText));

                kostData.setAddress(txtAlamat.getText());
                kostData.setDescription(txtDeskripsi.getText());
                kostData.setQuantity((int) spinnerQuantity.getValue());
                kostData.setCategory(String.valueOf(cmbCategory.getSelectedIndex() + 1));

                // Save to database
                String createdKost = BoardingHouseService.create(kostData);
                if (createdKost != null) {
                    Utils.showMessageDialog("Sukses", createdKost, "./img/success.gif", 100, 100);
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menyimpan data kost");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            tblKost.setModel(BoardingHouseService.getData());
        } else {
            try {
                BoardingHouseEntity kostData = new BoardingHouseEntity();
//				image = kostData.getImage();
                kostData.setId(Integer.parseInt(txtId.getText()));
                kostData.setName(txtNamaKost.getText());
//				kostData.setImage(jTextField1.getText());

//                String prevImage = jTextField1.getText();
                kostData.setSize(txtUkuran.getText());

                // Validate if the input for price is a number
                String priceText = txtHarga.getText();
                if (!priceText.matches("\\d+")) { // Check if the input contains only digits
                    JOptionPane.showMessageDialog(null, "Input harga harus angka");
                    return; // Exit the method
                }
                kostData.setPrice(Integer.parseInt(priceText));

                kostData.setAddress(txtAlamat.getText());
                kostData.setDescription(txtDeskripsi.getText());
                kostData.setQuantity((int) spinnerQuantity.getValue());
                kostData.setImage(String.valueOf(imageFile));
                System.out.println("image baru: " + imageFile);
                // buat field kategori! (it's hardcoded to "1" for now)
                kostData.setCategory(String.valueOf(cmbCategory.getSelectedIndex() + 1));

                // Save to database
                String updatedKost = BoardingHouseService.update(kostData, image);
                System.out.println("image awal: " + image);
                if (updatedKost != null) {
                    Utils.showMessageDialog("Sukses", updatedKost, "./img/success.gif", 100, 100);

                } else {
                    JOptionPane.showMessageDialog(null, "Gagal mengupdate data kost");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            tblKost.setModel(BoardingHouseService.getData());
        }

//        BoardingHouseService.getData();
	}//GEN-LAST:event_btnSimpanActionPerformed

	private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
	}//GEN-LAST:event_txtHargaActionPerformed

	private void txtUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkuranActionPerformed
        // TODO add your handling code here:
	}//GEN-LAST:event_txtUkuranActionPerformed

	private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtNamaKost.setText("");
        jTextField1.setText("");
        txtUkuran.setText("");
        txtHarga.setText("");
        txtAlamat.setText("");
        txtDeskripsi.setText("");
        spinnerQuantity.setValue(0);
        cmbCategory.setSelectedIndex(0);
	}//GEN-LAST:event_btnBatalActionPerformed

	private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int isConfirmed = Utils.showConfirmDialog("Warning", "Are you sure want to delete?", "./img/warning.gif", 100,
                100);
        if (isConfirmed == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            BoardingHouseEntity kostData = new BoardingHouseEntity();
            kostData.setId(Integer.parseInt(txtId.getText()));
            kostData.setImage(jTextField1.getText());
            String deleteData = BoardingHouseService.deleteById(kostData);

//			databaru = true;
            // Mengosongkan field setelah penghapusan
            if (deleteData.contains("berhasil")) {
                Utils.showMessageDialog("Success", deleteData, "./img/success.gif", 100, 100);
                txtId.setText("");
                txtNamaKost.setText("");
                jTextField1.setText("");
                txtUkuran.setText("");
                txtHarga.setText("");
                txtAlamat.setText("");
                txtDeskripsi.setText("");
                spinnerQuantity.setValue(0);
                cmbCategory.setSelectedIndex(0);
            }
        } catch (HeadlessException e) {
            Utils.showMessageDialog("Something went wrong", e.getMessage(), "./img/warning.gif", 120, 120);
        }
	}//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchKostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchKostMouseClicked
        // TODO add your handling code here:
        txtSearchKost.setText("");
    }//GEN-LAST:event_txtSearchKostMouseClicked

    private void txtSearchKostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKostKeyReleased
        // TODO add your handling code here:
        String name = txtSearchKost.getText();

        if (name != ("")) {
            tblKostAwal.setModel(BoardingHouseService.getDataByNameToTable(name));
        } else {
            tblKostAwal.setModel(BoardingHouseService.getDataKost());
        }
    }//GEN-LAST:event_txtSearchKostKeyReleased

    private void txtNamaKostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaKostMouseClicked
        // TODO add your handling code here:
        txtNamaKost.setText("");
    }//GEN-LAST:event_txtNamaKostMouseClicked

    private void txtAlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlamatMouseClicked
        // TODO add your handling code here:
        txtAlamat.setText("");
    }//GEN-LAST:event_txtAlamatMouseClicked

    private void txtHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaMouseClicked
        // TODO add your handling code here:
        txtHarga.setText("");
    }//GEN-LAST:event_txtHargaMouseClicked

    private void txtDeskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeskripsiMouseClicked
        // TODO add your handling code here:
        txtDeskripsi.setText("");
    }//GEN-LAST:event_txtDeskripsiMouseClicked

    private void txtUkuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUkuranMouseClicked
        // TODO add your handling code here:
        txtUkuran.setText("");
    }//GEN-LAST:event_txtUkuranMouseClicked

    private void tblKostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKostMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblKost.getSelectedRow();
            String tabel_klik = (tblKost.getModel().getValueAt(row, 0).toString());
            java.sql.Connection conn = (java.sql.Connection) services.database.Db.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from boarding_houses where id='" + tabel_klik + "'");
            if (sql.next()) {
                int id = sql.getInt("id");
                txtId.setText(String.valueOf(id));
                String name = sql.getString("name");
                txtNamaKost.setText(name);
                String address = sql.getString("address");
                txtAlamat.setText(address);
                String ukuran = sql.getString("size");
                txtUkuran.setText(ukuran);
                int price = sql.getInt("price");
                txtHarga.setText(String.valueOf(price));
                String description = sql.getString("description");
                txtDeskripsi.setText(description);
                int quantity = sql.getInt("quantity");
                spinnerQuantity.setValue(quantity);
                this.image = sql.getString("image");
                labelImage.setIcon(new AvatarIcon(image, 100, 100, 5));
                jTextField1.setText(image);

                databaru = false;

            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tblKostMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDataKost;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel iconAlamat;
    private javax.swing.JLabel iconDeskripsi;
    private javax.swing.JLabel iconHarga;
    private javax.swing.JLabel iconJumlahKamar;
    private javax.swing.JLabel iconKategori;
    private javax.swing.JLabel iconKategori1;
    private javax.swing.JLabel iconUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel nameKost;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTambah;
    private javax.swing.JPanel panelView;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JTable tblKost;
    private javax.swing.JTable tblKostAwal;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaKost;
    private javax.swing.JTextField txtSearchKost;
    private javax.swing.JTextField txtUkuran;
    // End of variables declaration//GEN-END:variables

}
