/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.Customer;

import services.boarding_houses.entities.BoardingHouseEntity;

import javax.swing.*;

/**
 * @author Bam
 */
public class DetailCard extends javax.swing.JPanel {
	BoardingHouseEntity data;

	/**
	 * Creates new form DetailCard
	 */
	public DetailCard(BoardingHouseEntity data) {
		this.data = data;
		initComponents();

		lblAlamat.setText(data.getAddress());

		lblDeskripsi.setText(data.getDescription());
		lblHarga.setText(String.valueOf(data.getPrice()));
		lblImg.setIcon(new ImageIcon(data.getImage()));
		lblKategori.setText(data.getCategory());
		lblNama.setText(data.getName());
		lblQty.setText(String.valueOf(data.getQuantity()));
		lblSize.setText(data.getSize());
		lblClose.setIcon(new ImageIcon("./img/Left.png"));


	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		lblDeskripsi = new javax.swing.JLabel();
		lblNama = new javax.swing.JLabel();
		lblSize = new javax.swing.JLabel();
		lblKategori = new javax.swing.JLabel();
		lblHarga = new javax.swing.JLabel();
		lblAlamat = new javax.swing.JLabel();
		lblQty = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		lblImg = new javax.swing.JLabel();
		lblClose = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel3.setPreferredSize(new java.awt.Dimension(821, 507));

		jScrollPane1.setHorizontalScrollBar(null);

		jPanel1.setPreferredSize(new java.awt.Dimension(821, 1000));

		jPanel2.setPreferredSize(new java.awt.Dimension(821, 507));
		jPanel2.setRequestFocusEnabled(false);

		jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(102, 102, 102));
		jLabel8.setText("Deskripsi");

		lblDeskripsi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
		lblDeskripsi.setToolTipText("");
		lblDeskripsi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		lblNama.setFont(new java.awt.Font("Poppins Black", 1, 24)); // NOI18N
		lblNama.setText("Nama");

		lblSize.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		lblSize.setText("ukuran");

		lblKategori.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		lblKategori.setText("Kategori");

		lblHarga.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		lblHarga.setText("Rp");

		lblAlamat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		lblAlamat.setText("Alamat");

		lblQty.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		lblQty.setText("Kamar");

		jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(102, 102, 102));
		jLabel9.setText("Ukuran    :");

		jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(102, 102, 102));
		jLabel10.setText("Kategori  :");

		jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(102, 102, 102));
		jLabel11.setText("Harga  :");

		jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(102, 102, 102));
		jLabel12.setText("Alamat    :");

		jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(102, 102, 102));
		jLabel13.setText("Kamar  :");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(72, 72, 72)
																.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addComponent(jLabel13)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																				.addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addComponent(jLabel11)
																				.addGap(18, 18, 18)
																				.addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(78, 78, 78)))
								.addContainerGap(138, Short.MAX_VALUE))
										);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(17, 17, 17)
								.addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(17, 17, 17)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9)
										.addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel11)
										.addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(13, 13, 13)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel13)
										.addComponent(jLabel10)
										.addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel12)
										.addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(42, 42, 42)
								.addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(153, Short.MAX_VALUE))
									  );

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(16, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
										);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(148, Short.MAX_VALUE))
									  );

		jScrollPane1.setViewportView(jPanel1);

		lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblCloseMouseClicked(evt);
			}
		});

		jButton1.setBackground(new java.awt.Color(0, 51, 153));
		jButton1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 14)); // NOI18N
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("Pesan");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblClose))
								.addContainerGap(70, Short.MAX_VALUE))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
										);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addGap(15, 15, 15)
								.addComponent(lblClose)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
								.addComponent(jButton1)
								.addGap(14, 14, 14))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
									  );

		add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
	}// </editor-fold>//GEN-END:initComponents

	private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
		// TODO add your handling code here:

		Kost kos = new Kost();
		DashboardCustomer.pn_utama.removeAll();
		DashboardCustomer.pn_utama.add(kos);
		DashboardCustomer.pn_utama.repaint();
		DashboardCustomer.pn_utama.revalidate();
	}//GEN-LAST:event_lblCloseMouseClicked

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton1ActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblAlamat;
	private javax.swing.JLabel lblClose;
	private javax.swing.JLabel lblDeskripsi;
	private javax.swing.JLabel lblHarga;
	private javax.swing.JLabel lblImg;
	private javax.swing.JLabel lblKategori;
	private javax.swing.JLabel lblNama;
	private javax.swing.JLabel lblQty;
	private javax.swing.JLabel lblSize;
	// End of variables declaration//GEN-END:variables
}
