/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client.Customer;

import static client.Customer.DashboardCustomer.pn_utama;
import java.util.ArrayList;
import services.boarding_houses.BoardingHouseService;
import services.boarding_houses.entities.BoardingHouseEntity;

/**
 *
 * @author Bam
 */
public class Kost extends javax.swing.JPanel {
ArrayList<BoardingHouseEntity> listOfKos;
    /**
     * Creates new form
     */
    public Kost() {
        initComponents();
         listOfKos = BoardingHouseService.getDataToEntity();
        icon_search.setIcon( new javax.swing.ImageIcon("./img/Search.png"));
        for (BoardingHouseEntity kos : listOfKos) {
                    renderCard(kos);
            }
       
    }
    
    private void renderCard(BoardingHouseEntity kos){
        Card card =  new Card(kos);
        pnKost.add(card);
        pnKost.repaint();
        pnKost.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfld_serach = new javax.swing.JTextField();
        btn_search = new javax.swing.JPanel();
        icon_search = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnKost = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(688, 501));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtfld_serach.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtfld_serach.setForeground(new java.awt.Color(151, 151, 151));
        txtfld_serach.setToolTipText("nama Kos");
        txtfld_serach.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtfld_serach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_serachActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(0, 51, 153));
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        icon_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_search.setAlignmentY(0.0F);
        icon_search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_searchLayout = new javax.swing.GroupLayout(btn_search);
        btn_search.setLayout(btn_searchLayout);
        btn_searchLayout.setHorizontalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_searchLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(icon_search)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        btn_searchLayout.setVerticalGroup(
            btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btn_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_searchLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(icon_search, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtfld_serach, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfld_serach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(770, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(770, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 400));

        pnKost.setMinimumSize(new java.awt.Dimension(720, 420));
        pnKost.setPreferredSize(new java.awt.Dimension(400, 623));
        pnKost.setRequestFocusEnabled(false);
        pnKost.setVerifyInputWhenFocusTarget(false);
        pnKost.setLayout(new java.awt.GridLayout(2, 4));
        jScrollPane1.setViewportView(pnKost);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfld_serachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_serachActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtfld_serachActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_searchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_search;
    private javax.swing.JLabel icon_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnKost;
    private javax.swing.JTextField txtfld_serach;
    // End of variables declaration//GEN-END:variables
}
